spring:
  jpa:
    show-sql: true
  datasource:
    url: "jdbc:mysql://${WC_MYSQL_AUTHORITY}/wellseecoding"
    username: "${WC_MYSQL_USERNAME}"
    password: "${WC_MYSQL_PASSWORD}"
    driver-class-name: "com.mysql.jdbc.Driver"
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: "${WC_NAVER_CLIENT_ID}"
            client-secret: "${WC_NAVER_CLIENT_SECRET}"
            redirect-uri: "${WC_ORIGIN}/login/oauth2/code/naver"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "POST"
          kakao:
            client-id: "${WC_KAKAO_CLIENT_ID}"
            client-secret: "${WC_KAKAO_CLIENT_SECRET}"
            redirect-uri: "${WC_ORIGIN}/login/oauth2/code/kakao"
            authorization-grant-type: "authorization_code"
            client-authentication-method: "POST"
        provider:
          naver:
            authorization-uri: "https://nid.naver.com/oauth2.0/authorize"
            token-uri: "https://nid.naver.com/oauth2.0/token"
            user-info-uri: "https://openapi.naver.com/v1/nid/me"
            user-name-attribute: "response"
          kakao:
            authorization-uri: "https://kauth.kakao.com/oauth/authorize"
            token-uri: "https://kauth.kakao.com/oauth/token"
            user-info-uri: "https://kapi.kakao.com/v2/user/me"
            user-name-attribute: "id"

wellseecoding:
  http:
    cookie-domain: "${WC_COOKIE_DOMAIN}"
    uris:
      sns-success: "${WC_SNS_SUCCESS_PAGE}"
      sns-failure: "${WC_SNS_FAILURE_PAGE}"
    access-token:
      shared-secret: "${WC_JWT_SHARED_SECRET}"
      timeout: 600
      claims:
        issuer: "${WC_JWT_ISSUER}"
    cors:
      origins: "${WC_CORS_ORIGINS}"