spring:
  jpa:
    show-sql: true
  datasource:
    url: "jdbc:mysql://${WC_MYSQL_AUTHORITY}/wellseecoding"
    username: "${WC_MYSQL_USERNAME}"
    password: "${WC_MYSQL_PASSWORD}"
    driver-class-name: "com.mysql.jdbc.Driver"

wellseecoding:
  http:
    uris:
      oauth2-success: "${WC_OAUTH2_SUCCESS_PAGE}"
      oauth2-failure: "${WC_OAUTH2_FAILURE_PAGE}"
    access-token:
      duration-in-seconds: 600
  jwt:
    jwe:
      algorithm: "dir"
      encryption-algorithm: "A256GCM"
      key: "${WC_JWE_KEY}"